### ISSUE TITLE
username column for sequelize table

### ISSUE THREAD

**Issue by stephenhuh** [afreymiller/chinese-democracy#37]
this doesnt need to be there @afreymiller  -- also the name attributes are wrong atm - it should be email, address not username, password for passport. LMK what u think u should do

**Comment by afreymiller** [comment]
I'll take re-define the table and fix the parameters issue, however, where do you see that it should be email, address?

**Comment by stephenhuh** [comment]
oops i meant email, password @afreymiller

**Comment by stephenhuh** [comment]
just to specify, when i say that the name attributes are wrong i mean that the html forms currently require me to specify name="username", name="password" which is probably some logic issue with the way passportjs expects the params.

**Comment by afreymiller** [comment]
'username' column deleted in sequelize, 'username' field attributes changed to 'email' in views.
