### ISSUE TITLE
password salting issue (hypothesized)

### ISSUE THREAD

**Issue by stephenhuh** [afreymiller/chinese-democracy#64]
$2a$10$tVDPGOT2wCBDo6Fr7QzYhO92BmyYv all passwords start with same random string.

**Comment by afreymiller** [comment]
Looking at the docs (https://www.npmjs.com/package/bcrypt-nodejs), it looks like the function we were using in the classMethod, hashSync, was used for encryption. We probably should have been using the 'hash' function instead.

**Comment by stephenhuh** [comment]
> The prefix "$2a$" or "$2b$" (or "$2y$") in a hash string in a shadow password file indicates that hash string is a bcrypt hash in modular crypt format.
